name: RainbowEdit
main: com.magicpowered.rainbowedit.RainbowEdit
version: '${project.version}'
author: JLING
api-version: 1.13
description: RainbowEdit plugin Edition by linlang
depend:
  - LinlangRuntimeBukkit

commands:
  re:
    description: Edit item names and lore
    usage: /<command> help
    aliases:
      - rainbowedit
      - rainbowe
      - redit

permissions:
  rainbowedit.use.name:
    description: 修改名称
    default: op
  rainbowedit.use.lore:
    description: 修改描述
    default: op
  rainbowedit.reload:
    description: 重载插件
    default: op
  rainbowedit.language:
    description: 查看插件当前语言
    default: op
  rainbowedit.testing:
    description: 执行琳琅集成测试命令
    default: op
