name: RainbowEdit
main: com.magicpowered.rainbowedit.RainbowEdit
version: 1.0.0.1
author: JLING
api-version: 1.12

commands:
  re:
    description: <name/~/add/+/set/@/before/>/after/</replace/#/preview/$/apply/./cancel/!/remove/-/clear/%>
    usage: /<command> <name/~/add/+/set/@/before/>/after/</replace/#/preview/$/apply/./cancel/!/remove/-/clear/%>
    aliases:
      - rainbowedit
      - rainbowe
      - redit
      - re
    tab-completions: com.magicpowered.rainbowedit.CommandListener

permissions:
  rainbowedit.use.name:
    description: 修改名称
    default: op
  rainbowedit.use.lore:
    description: 修改描述
    default: op
  rainbowedit.reload:
    description: 重载插件
    default: op